run:
  timeout: 5m
  go: "1.22.0"

linters:
  enable:
    # Code format and style
    - gofmt
    - goimports
    - gocritic
    - stylecheck
    - whitespace

    # Code correctness
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck

    # Code simplification
    - unconvert
    - unused
    - unparam

    # Security
    - gosec
    - noctx

    # Complexity and duplication
    - gocyclo
    - dupl
    - goconst

    # Documentation and naming
    - misspell
    - godox
    - goprintffuncname

    # Other
    - mnd  # Replacing deprecated gomnd
    - nakedret
    - nolintlint
    - rowserrcheck

linters-settings:
  # Complexity checks
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
    
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult  # Disable unnamed result check

issues:
  # Exclude specific linters from test files and examples
  exclude-rules:
    # Test files can use magic numbers and may be more complex
    - path: _test\.go
      linters:
        - gomnd # Allow magic numbers in tests
        - gocyclo # Allow more complex test functions
        - dupl # Allow similar test cases

    # Example code should be simple and straightforward
    - path: examples/
      linters:
        - gomnd # Allow magic numbers in examples
        - gocyclo # Allow simpler but maybe not optimal code
        - dupl # Allow repeated examples
        - gosec # Allow simplified security for examples
