name: Security Scan Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

permissions:
  contents: read
  security-events: write

jobs:
  gosec-matrix:
    name: Security Scan on Multiple Platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Continue with other matrix jobs even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.24']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Verify dependencies
        shell: bash
        run: |
          go mod download
          go mod tidy
          # Ensure go.sum exists
          if [ ! -f "go.sum" ]; then
            touch go.sum
          fi

      # Use the gosec GitHub Action for Windows
      - name: Run gosec with GitHub Action (Windows)
        if: runner.os == 'Windows'
        uses: securego/gosec@v2.22.5
        with:
          args: "-fmt sarif -out gosec-results.sarif ./stl"
          
      # Direct installation for Linux and macOS
      - name: Install and run gosec (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # Direct installation of gosec
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          # Verify gosec installation
          which gosec || echo "gosec not found in PATH"
          # Run gosec with full output
          gosec -fmt=json -out=gosec-results.json ./stl || echo "gosec JSON output failed"
          gosec -fmt=sarif -out=gosec-results.sarif ./stl || echo "gosec SARIF output failed"
          # Show results summary
          gosec ./stl || echo "gosec scan failed"
          
      - name: Upload gosec results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gosec-results.sarif
          category: gosec-${{ matrix.os }}
